import { useSession } from 'next-auth/react';
import Head from 'next/head';
import { api } from '@/utils/api';

export default function Home() {
  const hello = api.post.hello.useQuery({ text: 'from tRPC' });
  const { data: sessionData } = useSession();

  const isLoggedIn = Boolean(sessionData?.user);

  return (
    <>
      <Head>
        <title>Piedule</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>Homepage</main>
    </>
  );
}
